### ISSUE TITLE
deploying same proxy with different endpoint

### ISSUE THREAD

**Issue by aglamela** [scastria/terraform-provider-apigee#12]
Hi, 

When changing  inside a proxy the  <HTTPProxyConnection><BasePath>/examplepath</BasePath> to a  <HTTPProxyConnection><BasePath>/examplepath2</BasePath>, it is deploying correctly the new proxy, but in my opinion, it should undeploy the old proxy using the old /examplepath. 

Maybe it would be interesting to add a new variable to configure this behavior.

**Comment by scastria** [comment]
I was relying on the Apigee Management API to undeploy the existing proxy revision with the override = true parameter.  Either there is a bug in the Apigee Management API in the case where the basepath changes or this was intentional.  In either case, I will see what I can do to force the undeployment.  If somebody else wants to keep the existing behavior, I will let them submit an issue and then I will add some extra parameter to make it configurable.

**Comment by scastria** [comment]
Try v0.1.34 when it is done building

**Comment by scastria** [comment]
Can I close this issue?

**Comment by aglamela** [comment]
Let me a few days to test it, during this weekend i am out. Thank you!

**Comment by aglamela** [comment]
It is working perfectly! Thank you very much!
