### ISSUE TITLE
Repo not functioning well in Apigee Hybrid 

### ISSUE THREAD

**Issue by Devajeet1995** [scastria/terraform-provider-apigee#13]
Hello, I have a hybrid setup and I installed terraform on my VM. Now when I started to deploy the proxy to my hybrid account by using your repo where I mentioned my username and password, I am getting 401 unauthorized even after MFA is disabled. Usually, this happens when you have mistyped your password or you have MFA enabled. But it's not the same in my case. However, the same repo is working well in my Apigee Edge eval account. So what needs to be changed for the apigee hybrid account? Attaching the screenshots for reference
![terraform_issue](https://user-images.githubusercontent.com/36272733/108706152-330a6300-7534-11eb-97fe-352c38302d5f.PNG)
.
![terraform](https://user-images.githubusercontent.com/36272733/108705664-9f389700-7533-11eb-8eac-29d398f58634.PNG)

**Comment by scastria** [comment]
The best thing to do to debug this is to turn on TF_LOG=DEBUG environment variable.  When that is on, the apigee provider will output every single REST call it makes to your Apigee server.  You can find the one that is failing and see if you can recreate the problem by making the exact same REST call in PostMan or Curl or something like that.  If you are able to successfully make the exact same REST call, in PostMan, then there is a bug in the Apigee provider.  Instead, if you recreate the same problem and get back a 401 Unauthorized error, then the issue is on your side and perhaps MFA is enabled or you did mistype your password, etc.

Keep in mind that creating a proxy is a difficult REST call to make using Postman or Curl so you might want test with something simpler, like a KVM or Cache object.  Or even simpler is to use terraform import and see if you can import an existing proxy into terraform.  That will have the Apigee provider make a GET call instead of a POST call for your proxy which is also a simpler REST call to recreate in PostMan.

**Comment by Devajeet1995** [comment]
Hi, thanks for the solution. But I am a newbie to Terraform and I don't really know how to set and output the log. I have explored some docs as well but nowhere mentioned about where to set and how to define the variable inside the provider. So it would be good if you provide or at least suggest a way to proceed further.

**Comment by Devajeet1995** [comment]
Hi Shawn, thanks for the response. After digging a bit into the issue and looking at the log file I saw that the host you are calling is **https://api.enterprise.apigee.com**. However Apigee hybrid uses **https://apigee.googleapis.com** in all the management APIs. Because of which I am getting the 401 unauthorized error in Postman too. Google uses a different technique to authenticate the users in the case of a Hybrid setup. Attached a terraform config code for the reference.
 `terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.5.0"
    }
  }
}

provider "google" {

  credentials = file("<NAME>.json")

  project = "<PROJECT_ID>"
  region  = "us-central1"
  zone    = "us-central1-c"
}`

**Comment by scastria** [comment]
Since you closed this issue, I am assuming you found out that you can specify the server and ports in your provider configuration.

**Comment by Devajeet1995** [comment]
Yes, Shawn. Thanks to this wonderful provider.
