### ISSUE TITLE
add override flag to  apigee_shared_flow_deployment

### ISSUE THREAD

**Issue by koooni** [scastria/terraform-provider-apigee#47]
hi
i am having issues when i try to apply a sharedflow which already exists (created manually).
i get the following exception:

`Error: Status 400: Message: Bad Request: { "error": { "code": 400, "message": "deployment validations failed", "status": "FAILED_PRECONDITION", "details": [ { "@type": "type.googleapis.com/google.rpc.PreconditionFailure", "violations": [ { "type": "CONFLICTING_DEPLOYMENT", "subject": "organizations/apigee-develop/sharedflows/my-sharedflow/revisions/1", "description": "Only one revision can be deployed at a time, use the override flag to replace." } ] }, { "@type": "type.googleapis.com/google.rpc.RequestInfo", "requestId": "6440894081113900951" } ] } }
with apigee_shared_flow_deployment.my-sharedflow-mr-develop
on apigee-resources.tf line 213, in resource "apigee_shared_flow_deployment" "my-sharedflow-mr-develop":
resource "apigee_shared_flow_deployment" "my-sharedflow-mr-develop" {`

would it be possible to add this override flag to apigee_shared_flow_deployment so that it can be overriden?
the problem is that this deployment is already used in other flows so usually u can't delete and recreate it that easily.

**Comment by scastria** [comment]
The override flag is being used already. The problem is TF doesn’t know you already created it manually so it is trying to create it as new. Creating it brand new does not allow for the override flag. The override flag is only for updating. Therefore, the fix is for you to run a terraform import command to import the manually created shared flow into TF. then when you apply, TF will do an update with the override flag. The docs for the Apigee TF provider describe how to import each resource type.
